#!/usr/bin/env python3
import sys
sys.path.append('lib/python')

from kantoo import dockerdriver
import click
import os

@click.command()
@click.option('--skip',type=str,help='The name of a bash plugin in the config file to skip',multiple=True)
@click.option('--config',type=click.Path(exists=True), help='A relative path to an hjson file')
@click.option('--pretend',is_flag=True,help="skip all bash plugins")
@click.option('--interactive',is_flag=True,default=False,help='interact with the container after each plugin is applied')
def _dockerdriver(skip,config,pretend,interactive):
    dockerdriver(os.path.dirname(os.path.realpath(__file__)), config,skip,pretend,interactive)

if __name__ == '__main__':
    _dockerdriver()

