#!/usr/bin/env python3
import sys
sys.path.append('lib/python')

import stalker
import pathlib
import click
import eliot

def stdout(message):
    if message.get('message_type') == 'info':
        if 'msg' in message.keys():
            print(message.get('msg'))

eliot.add_destinations(stdout)
eliot.to_file(open(f"{pathlib.Path('.').absolute()}/logs/eliot.txt",'wb'))

@click.command()
@click.option('--config',type=click.Path(exists=True), help='A relative path to an hjson file of stalks')
def _stalker(config):
    s = stalker.sd(pathlib.Path('.').absolute(), pathlib.Path(config))

if __name__ == '__main__':
    _stalker()

