#!/usr/bin/env python3
import sys
sys.path.append('lib/python')

import stalker
import pathlib
import click
import eliot

# def stdout(message):
#     if message.get('message_type') == 'info':
#         if 'msg' in message.keys():
#             print(message.get('msg'))
#
# eliot.add_destinations(stdout)

eliot.to_file(open(f"{pathlib.Path('.').absolute()}/logs/eliot.txt",'wb'))

@click.command()
@click.option('--config',type=click.Path(exists=True), help='A relative path to an hjson file of stalks')
@click.option('--watch_stdout',is_flag=True,help='Watch the output of each container run')
@click.option('--eliot_info',is_flag=True,help='Watch the info messages of the eliot log')
def _stalker(config,watch_stdout,eliot_info):
    if eliot_info:
        def stdout(message):
            if message.get('message_type') == 'info':
                if 'msg' in message.keys():
                    print(message.get('msg'))
        eliot.add_destinations(stdout)

    s = stalker.sd(pathlib.Path('.').absolute(), pathlib.Path(config),watch_stdout)

if __name__ == '__main__':
    _stalker()

